language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

install:
  - yarn install --frozen-lockfile

script: yarn run ci
